---
- name: Manage Minecraft Server
  hosts: all
  become: true  # Run all tasks with sudo
  tasks:

    - name: Stop Minecraft server
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: stopped

    - name: Ensure the main Minecraft world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld
        state: absent

    - name: Ensure the Nether world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_nether
        state: absent

    - name: Ensure the End world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_the_end
        state: absent

    - name: Start Minecraft server
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: started

    - name: Wait for Minecraft service to be started
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: started
      register: result

    - name: Print Minecraft server status
      ansible.builtin.debug:
        msg: "Minecraft server status: {{ result }}"
