---
- name: Manage Minecraft Server
  hosts: minecraft
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    
  tasks:
    - name: Gather facts
      setup:

    - name: Stop Minecraft server
      systemd:
        name: minecraft.service
        state: stopped

    - name: Wait for 10 seconds to ensure the service has fully stopped
      pause:
        seconds: 10

    - name: Reload systemd to ensure updated configuration
      command: systemctl daemon-reload

    - name: Ensure the main Minecraft world directory is absent
      file:
        path: /home/mcserver/minecraft/forge_server_1.16.5/Auduns_world
        state: absent

    - name: Ensure the Nether world directory is absent
      file:
        path: /home/mcserver/minecraft/forge_server_1.16.5/Auduns_world_nether
        state: absent

    - name: Ensure the End world directory is absent
      file:
        path: /home/mcserver/minecraft/forge_server_1.16.5/Auduns_world_the_end
        state: absent
    
    - name: Remove banned-players.json
      ansible.builtin.file:
        path: /home/mcserver/minecraft/forge_server_1.16.5/banned-players.json
        state: absent

    - name: Start Minecraft server
      systemd:
        name: minecraft.service
        state: started

    - name: Pause for 10 seconds to ensure Minecraft service is fully started
      pause:
        seconds: 10

    - name: Get Minecraft server status
      command: systemctl status minecraft.service
      register: minecraft_status

    - name: Print Minecraft server status
      debug:
        msg: "{{ minecraft_status.stdout }}"
