---
- name: Manage Minecraft Server
  hosts: all
  become: true  # Run all tasks with sudo
  tasks:

    - name: Send in-game warning message about new season
      ansible.builtin.shell:
        cmd: "screen -S minecraft -p 0 -X stuff 'say Starting new season in 30 seconds!^M'"
        chdir: /home/mcserver/minecraft

    - name: Pause for 5 seconds to allow the warning message to be seen
      pause:
        seconds: 5

    - name: Send in-game countdown messages
      ansible.builtin.shell:
        cmd: |
          for i in {30..1}; do
            screen -S minecraft -p 0 -X stuff "say Restarting in $i seconds!^M"
            sleep 1
          done
        chdir: /home/mcserver/minecraft

    - name: Stop Minecraft server
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: stopped

    - name: Ensure the main Minecraft world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld
        state: absent

    - name: Ensure the Nether world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_nether
        state: absent

    - name: Ensure the End world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_the_end
        state: absent

    - name: Remove banned-players.json
      ansible.builtin.file:
        path: /home/mcserver/minecraft/banned-players.json
        state: absent

    - name: Start Minecraft server
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: started

    - name: Pause for 5 seconds to ensure Minecraft service is fully started
      pause:
        seconds: 5

    - name: Wait for Minecraft service to be started
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: started
      register: result

    - name: Print Minecraft server status
      ansible.builtin.debug:
        msg: "Minecraft server status: {{ result }}"

