---
- name: Manage Minecraft Server
  hosts: minecraft
  become: yes

  tasks:
    - name: Gather facts
      setup:

    - name: Stop Minecraft server
      systemd:
        name: minecraftserver.service
        state: stopped

    - name: Ensure the main Minecraft world directory is absent
      file:
        path: /home/mcserver/minecraft/Audunsworld
        state: absent

    - name: Ensure the Nether world directory is absent
      file:
        path: /home/mcserver/minecraft/Nether
        state: absent

    - name: Ensure the End world directory is absent
      file:
        path: /home/mcserver/minecraft/The_End
        state: absent

    - name: Start Minecraft server
      systemd:
        name: minecraftserver.service
        state: started

    - name: Pause for 5 seconds to ensure Minecraft service is fully started
      pause:
        seconds: 5

    - name: Print Minecraft server status
      systemd:
        name: minecraftserver.service
        state: started
      register: minecraft_status

    - name: Print Minecraft server status
      debug:
        msg: "{{ minecraft_status }}"
