---
- name: Manage Minecraft Server
  hosts: minecraft
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    
  tasks:
    - name: Gather facts
      setup:

    - name: Stop Minecraft server
      systemd:
        name: minecraftserver.service
        state: stopped

    - name: Ensure the main Minecraft world directory is absent
      file:
        path: /home/mcserver/minecraft/Audunsworld
        state: absent

    - name: Ensure the Nether world directory is absent
      file:
        path: /home/mcserver/minecraft/Audunsworld_nether
        state: absent

    - name: Ensure the End world directory is absent
      file:
        path: /home/mcserver/minecraft/Audunsworld_the_end
        state: absent
    
    - name: Remove banned-players.json
      ansible.builtin.file:
        path: /home/mcserver/minecraft/banned-players.json
        state: absent

    - name: Start Minecraft server
      systemd:
        name: minecraftserver.service
        state: started

    - name: Pause for 5 seconds to ensure Minecraft service is fully started
      pause:
        seconds: 5

    - name: Print Minecraft server status
      systemd:
        name: minecraftserver.service
        state: started
      register: minecraft_status

    - name: Print Minecraft server status
      debug:
        msg: "{{ minecraft_status }}"
