---
- name: Manage Minecraft Server
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    force_reset_world: true  # Set to true if you want to reset world directories

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Stop Minecraft server
      ansible.builtin.systemd:
        name: minecraft.service
        state: stopped

    - name: Wait for 3 seconds to ensure the service has fully stopped
      ansible.builtin.pause:
        seconds: 3

    - name: Reload systemd to ensure updated configuration
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Ensure the main Minecraft world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld
        state: absent
      when: force_reset_world

    - name: Ensure the Nether world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_nether
        state: absent
      when: force_reset_world

    - name: Ensure the End world directory is absent
      ansible.builtin.file:
        path: /home/mcserver/minecraft/Audunsworld_the_end
        state: absent
      when: force_reset_world

    - name: Remove banned-players.json
      ansible.builtin.file:
        path: /home/mcserver/minecraft/banned-players.json
        state: absent

    - name: Start Minecraft server as root
      ansible.builtin.systemd:
        name: minecraft.service
        state: started

    - name: Pause for 6 seconds to ensure Minecraft service is fully started
      ansible.builtin.pause:
        seconds: 6

    - name: Verify Minecraft service is active
      ansible.builtin.command:
        cmd: systemctl is-active minecraft.service
      register: service_status
      retries: 5
      delay: 3
      until: service_status.stdout == "active"

    - name: Print Minecraft server status
      ansible.builtin.command:
        cmd: systemctl status minecraft.service
      register: minecraft_status

    - name: Debug Minecraft server status
      ansible.builtin.debug:
        msg: "{{ minecraft_status.stdout }}"
