- name: Apt Update and Force Reboot
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Update System Package Cache
      apt:
        update_cache: yes

    - name: Force Reboot the System
      reboot:
        reboot_timeout: 600
