---
- name: Restart Minecraft Server to Unban Players
  hosts: all
  become: true  # Run all tasks with sudo
  tasks:

    - name: Send in-game warning message about impending restart
      ansible.builtin.shell:
        cmd: "screen -S minecraft -p 0 -X stuff 'say Server omstart om 10 sekunder for å oppheve bannlysning av spillere!^M'"
        chdir: /home/mcserver/minecraft
      become: true
      become_user: mcserver

    - name: Countdown before restart
      ansible.builtin.shell:
        cmd: |
          for i in {10..1}; do
            screen -S minecraft -p 0 -X stuff "say Omstart om $i sekunder!^M"
            sleep 1
          done
        chdir: /home/mcserver/minecraft
      become: true
      become_user: mcserver

    - name: Stop Minecraft server
      ansible.builtin.systemd:
        name: minecraftserver.service
        state: stopped
      become: true

    - name:
