---
- name: Update, upgrade, and reboot servers
  hosts: Ubuntu_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Reboot the server if necessary
      reboot:
        when: ansible_facts['os_family'] == "Debian" and ansible_distribution == "Ubuntu"
        reboot_timeout: 600
