---
- name: Update, upgrade, and reboot servers
  hosts: Ubuntu_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache validity time in seconds

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoclean: yes
        autoremove: yes

    - name: Reboot the server if necessary
      reboot:
        reboot_timeout: 600
