- name: Upgrade and Reboot
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update System Package Cache
      apt:
        update_cache: yes

    - name: Upgrade System Packages
      apt:
        upgrade: full

    - name: Reboot the system if needed
      reboot:
        reboot_timeout: 600
      register: reboot_result
      ignore_errors: yes

    - name: Wait for the server to come back online
      wait_for:
        port: 22
        delay: 15
        timeout: 300
      when: reboot_result is defined and reboot_result.changed
